{
  "formatVersion": "1.1",
  "component": {
    "group": "com.recursive_pineapple",
    "module": "matter_manipulator",
    "version": "v0.1.0-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "zone.rong",
          "module": "mixinbooter",
          "version": {
            "requires": "10.6"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.cleanroommc",
          "module": "modularui",
          "version": {
            "requires": "3.1.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "24.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "matter_manipulator-v0.1.0-alpha-dev.jar",
          "url": "matter_manipulator-v0.1.0-alpha-dev.jar",
          "size": 4233877,
          "sha512": "0e82ff5de2d7c3dbdc9e29f57e897f1b0444f1de36356b47f97a1a0cc2bdbd8432d6c74b3bba6f6aa0e426cfa96802a61876194db68b113006cfacc8aba9da6d",
          "sha256": "9201aec426cefb9262d6c466208c070176fc1c6aa521ae7bc3d784af0b1921ab",
          "sha1": "ddd83e7c9603a8550a924cf3427f3a3c08f51b65",
          "md5": "7baec189bdd622933a02247561d2f9e1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei_1.12.2",
          "version": {
            "requires": "4.16.1.302"
          }
        },
        {
          "group": "curse.maven",
          "module": "top-245211",
          "version": {
            "requires": "2667280"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.7"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.7"
          }
        },
        {
          "group": "zone.rong",
          "module": "mixinbooter",
          "version": {
            "requires": "10.6"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.cleanroommc",
          "module": "modularui",
          "version": {
            "requires": "3.1.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "matter_manipulator-v0.1.0-alpha-dev.jar",
          "url": "matter_manipulator-v0.1.0-alpha-dev.jar",
          "size": 4233877,
          "sha512": "0e82ff5de2d7c3dbdc9e29f57e897f1b0444f1de36356b47f97a1a0cc2bdbd8432d6c74b3bba6f6aa0e426cfa96802a61876194db68b113006cfacc8aba9da6d",
          "sha256": "9201aec426cefb9262d6c466208c070176fc1c6aa521ae7bc3d784af0b1921ab",
          "sha1": "ddd83e7c9603a8550a924cf3427f3a3c08f51b65",
          "md5": "7baec189bdd622933a02247561d2f9e1"
        }
      ]
    },
    {
      "name": "reobfElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "srg",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "matter_manipulator-v0.1.0-alpha.jar",
          "url": "matter_manipulator-v0.1.0-alpha.jar",
          "size": 4274765,
          "sha512": "c1058a05f134556db818a52f3cc900749ba30b0f13c123305ae0d668b415fd8ca2bafecb8c841cd4a623e7646cf7f4a9a9a34a84e551a75d9da01081fe617d0e",
          "sha256": "f947cb943a875da708444f250370ad5834e470c55d9f7a0beda3c06dabb96f8e",
          "sha1": "90d60700c1c7d154aa50b442d28d638cd51c1006",
          "md5": "91aaeac54a2d4f5bc8dfeaa83e2ed91b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "matter_manipulator-v0.1.0-alpha-sources.jar",
          "url": "matter_manipulator-v0.1.0-alpha-sources.jar",
          "size": 377569,
          "sha512": "9145a4b248a0e994d578f310d6f993f7eec9e9df74f333225db9a58049b3dbf1cef68c737b5d9d0894e59d763342589868c2b67d82eaa9eb00093dc4485b19c2",
          "sha256": "d4d6b562e75ac09ea2126598317ae11d2ee9e3c28606df14e8d3c89d50a39718",
          "sha1": "dc71590e207bb6dff41d5adc0bcfcb555ada6b0b",
          "md5": "97ab0fdb0bfdcb8208d1e5875502e0a6"
        }
      ]
    }
  ]
}
