{
  "formatVersion": "1.1",
  "component": {
    "group": "com.recursive_pineapple",
    "module": "matter_manipulator",
    "version": "v0.1.3-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "zone.rong",
          "module": "mixinbooter",
          "version": {
            "requires": "10.6"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.cleanroommc",
          "module": "modularui",
          "version": {
            "requires": "3.1.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "24.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "matter_manipulator-v0.1.3-alpha-dev.jar",
          "url": "matter_manipulator-v0.1.3-alpha-dev.jar",
          "size": 4299756,
          "sha512": "4f6877609177a3e4aad72d9acacb8f1d6f90664f0585a4421529d9c728ecfbe73d534ec88bcb294f13abea060dc863e70468e2f12fda668bb33db9f2fd428be2",
          "sha256": "665d36ce0cc476f6c9c2bcf5efa01e05cc9e6e535e7b727c9a3468456aca2931",
          "sha1": "15d33074232093a4217dfe5a630035ec2f8d8de7",
          "md5": "5c4d225572c3a09a4c53dd33e88e460a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei_1.12.2",
          "version": {
            "requires": "4.16.1.302"
          }
        },
        {
          "group": "curse.maven",
          "module": "top-245211",
          "version": {
            "requires": "2667280"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.7"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.7"
          }
        },
        {
          "group": "zone.rong",
          "module": "mixinbooter",
          "version": {
            "requires": "10.6"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.cleanroommc",
          "module": "modularui",
          "version": {
            "requires": "3.1.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "matter_manipulator-v0.1.3-alpha-dev.jar",
          "url": "matter_manipulator-v0.1.3-alpha-dev.jar",
          "size": 4299756,
          "sha512": "4f6877609177a3e4aad72d9acacb8f1d6f90664f0585a4421529d9c728ecfbe73d534ec88bcb294f13abea060dc863e70468e2f12fda668bb33db9f2fd428be2",
          "sha256": "665d36ce0cc476f6c9c2bcf5efa01e05cc9e6e535e7b727c9a3468456aca2931",
          "sha1": "15d33074232093a4217dfe5a630035ec2f8d8de7",
          "md5": "5c4d225572c3a09a4c53dd33e88e460a"
        }
      ]
    },
    {
      "name": "reobfElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "srg",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "matter_manipulator-v0.1.3-alpha.jar",
          "url": "matter_manipulator-v0.1.3-alpha.jar",
          "size": 4341464,
          "sha512": "433f911d734627269713f52cec1a50386d410bc573d54ba3b3df5d59f2793a309be34fe34826260584e84861f6d740acf040cab003bb5e15c997ebe32eb86b8a",
          "sha256": "9b8048ef220bc96b6c29c1b216f1c45b6eda7769e213bdeb6ddbaad1807b2082",
          "sha1": "d6e9278df68725f33326678e3c3d5a04bd363579",
          "md5": "a6edc468d968d366ca3a5383b9f33f24"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "matter_manipulator-v0.1.3-alpha-sources.jar",
          "url": "matter_manipulator-v0.1.3-alpha-sources.jar",
          "size": 384297,
          "sha512": "d55355f9929538223b591b2c2af2a65982b3818cf5d0eb2aa208cfe12c920d5d159e48e7c72b3f3174470f4d25da80f64f7bbfe991adc5bae61258f4d52c333d",
          "sha256": "abdb12150aebfc8ec15c623a6f054b4d628b1cbb32e4df22f3ae36fe941a4aad",
          "sha1": "7d932acd5e4755910ee892c3a01a3d05bc20e73a",
          "md5": "0a29f342ff84c1054d3fad67b3b9d4d5"
        }
      ]
    }
  ]
}
